version: '3.8'
services:
  web:
    image: python:3.9-slim
    container_name: aenzbi-odoo
    command: python /app/main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: aenzbi-odoo-db
    environment:
      POSTGRES_DB: aenzbi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
